# Homebrew taps
tap "homebrew/bundle"

# Version control
brew "git"
brew "git-lfs"
brew "git-cliff"
brew "gh"
brew "yadm"

# Shell
brew "bash-completion"
brew "zsh"
brew "tmux"
brew "fzf"

# System
brew "gnupg"
brew "htop"
brew "tree"

# Network
brew "wget"
brew "curl"

# Development
brew "vim"
brew "jq"
brew "yq"
brew "bat"
brew "just"

# macOS
brew "mas"

# Essential casks, in order of configuration
cask "1password"
cask "1password-cli"
cask "ghostty"
cask "raycast"
cask "bartender"
cask "visual-studio-code"
cask "zed"
cask "soundsource"

# Shell prompts
brew "oh-my-posh"

# Browsers & browsing-related
cask "choosy"
cask "arc"
cask "brave-browser"
cask "firefox"
cask "google-chrome"
cask "tor-browser"
cask "raindropio"

# Development
cask "jetbrains-toolbox"
cask "docker"
cask "google-cloud-sdk"
cask "gcloud-cli"

# Essential AI
cask "chatgpt"

# Fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-iosevka"
cask "font-iosevka-nerd-font"

# Video
cask "elmedia-player"

# Drivers
cask "logi-options-plus"
